#!/usr/bin/env python

import httplib2
import os
import sys

from netscaler_cli import *

parser = initializeOptions(usage="usage: %prog [options] virtual_server service operation")

(options,args) = parser.parse_args()
if len(args) != 3:
    parser.error("No virtual service, service name or operation given")

vserver_name = args[0]
service_name = args[1]
operation = args[2]

if operation not in ['get', 'enable', 'disable']:
    sys.exit("Invalid operation: " + operation)

log = initializeLog(logger_name=sys.argv[0])

if options.verbose:
    log.setLevel(logging.INFO)
    httplib2.debuglevel = 10
if options.quiet:
    log.setLevel(logging.ERROR)
    httplib2.debuglevel = 0

config = initializeConfigParser(options.credentials_file)
log.info("creds: %s" % config)

client = httplib2.Http(os.path.join(os.environ['HOME'], '.cache'))
client.add_credentials(config['username'], config['password'])

method = 'GET'
request = config['ws_url'] + '/virtserver/' + vserver_name + \
	  '/service/' + service_name + '/'
if operation == 'enable':
    method = 'PUT'
    request = request + 'enable/'
elif operation == 'disable':
    method = 'PUT'
    request = request + 'disable/'
else:
    pass

response, body = client.request(request, method=method)
log.info("response = %s" % response)
log.info("body = %s" % body)

if response.status != 200:
    if options.quiet:
	sys.exit(1)
    else:
	sys.exit(body)

print body
sys.exit(0)
